"""add section to recipe_instructions

Revision ID: 855f80505379
Revises: fdb4e7eb210c
Create Date: 2026-09-25 12:50:31.048463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '855f80505379'
down_revision: Union[str, Sequence[str], None] = 'fdb4e7eb210c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_instructions', sa.Column('section', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_instructions', 'section')
    # ### end Alembic commands ###
