"""add user_id to recipes

Revision ID: 9ee2926235ec
Revises: 36843aedb673
Create Date: 2026-09-16 13:03:44.516389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee2926235ec'
down_revision: Union[str, Sequence[str], None] = '36843aedb673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_recipes_user_id_users', 'recipes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_recipes_user_id_users', 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'user_id')
    # ### end Alembic commands ###
